engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      python_version: 3
  pep8:
    enabled: true
ratings:
  paths:
  - "**.py"
# exclude_paths:
# - tests/
